import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-primary">
      <div className="max-w-3xl mx-auto px-6 py-16 space-y-8">
        <div className="space-y-2">
          <Link
            href="/"
            className="text-sm text-accent hover:underline"
          >
            &larr; Back to home
          </Link>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-text-tertiary text-sm">
            Last updated: February 15, 2026
          </p>
        </div>

        <div className="prose prose-invert max-w-none space-y-6 text-text-secondary">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using FilmMatch AI, you agree to be bound by
              these Terms of Service. If you do not agree, please do not use
              the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              2. Description of Service
            </h2>
            <p>
              FilmMatch AI is an AI-powered movie recommendation engine that
              helps individuals and groups find movies to watch. The service
              uses data from The Movie Database (TMDB) and Anthropic&apos;s
              Claude AI to generate personalized recommendations.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              3. User Accounts
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>You may use the service without an account (limited features)</li>
              <li>Account creation requires a valid email address</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must be at least 13 years old to create an account</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              4. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Abuse the API or attempt to circumvent rate limits</li>
              <li>Attempt to inject malicious content into AI prompts</li>
              <li>Use automated systems to scrape or overload the service</li>
              <li>Share content that is illegal, harmful, or offensive through the platform</li>
              <li>Impersonate other users or entities</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              5. Recommendations Disclaimer
            </h2>
            <p>
              Recommendations are generated by AI and are provided for
              entertainment purposes. We do not guarantee that recommendations
              will match your tastes. Movie availability on streaming services
              may change and we cannot guarantee real-time accuracy of
              availability data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              6. Intellectual Property
            </h2>
            <p>
              Movie data, posters, and metadata are provided by TMDB and are
              subject to their terms of use. The FilmMatch AI brand, design,
              and code are proprietary. User-generated content (preferences,
              reviews) remains yours.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              7. Service Availability
            </h2>
            <p>
              We strive for high availability but do not guarantee
              uninterrupted service. We may modify, suspend, or discontinue
              features at any time. We will provide reasonable notice for
              significant changes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              8. Limitation of Liability
            </h2>
            <p>
              FilmMatch AI is provided &quot;as is&quot; without warranties of
              any kind. We are not liable for any damages arising from your
              use of the service, including but not limited to inaccurate
              recommendations or service downtime.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              9. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of
              the service after changes constitutes acceptance of the new
              terms. We will notify users of significant changes via email.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-text-primary">
              10. Contact
            </h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a
                href="mailto:legal@filmmatch.ai"
                className="text-accent hover:underline"
              >
                legal@filmmatch.ai
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
